//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Semester2Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderCost
    {
        public int Id { get; set; }
        public string Stone { get; set; }
        public string Wood { get; set; }
        public string Thatch { get; set; }
        public string Metal { get; set; }
        public string CementingPaste { get; set; }
        public string Crystal { get; set; }
        public string Polymer { get; set; }
        public int OrderId { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
